feat: add the shell components
webzard-io/dovetail-v2 pull request #161
Opened 2024-06-06 06:12 UTC by MrWindlike

新增 Shell 组件方便连接各资源的终端，终端默认带有「搜索」、「调整字体大小」、「下载终端内容」、「清空的功能」。

并基于 Shell 提供 PodShell 来连接 k8s 原生 API 提供的 Pod 终端。

2024-06-19 06:29 UTC, tanbowensg commented
我看到有很多.js文件，是不是应该放到PodShell组件里面，而不是全局？

2024-09-04 02:34 UTC, MrWindlike commented on packages/refine/tools/pod-exec.ts
> +import { Plugin } from 'vite';
这个文件用于开发时代理 ws 连接。

2024-09-04 05:50 UTC, tanbowensg requested changes

2024-09-04 05:50 UTC, tanbowensg commented on packages/refine/src/components/PodShellModal/PodShell.tsx
> +    const message = `4${base64Encode(
4是什么？

2024-09-04 05:50 UTC, tanbowensg commented on packages/refine/src/components/Shell/index.tsx
> +export const Shell = React.forwardRef<ShellHandler, ShellProps>(function Shell(props: ShellProps, ref) {
这个文件里面多补充点注释吧，以免以后会忘

2024-09-05 06:45 UTC, MrWindlike commented on packages/refine/src/pages/deployments/list/index.tsx
> +import React, { useEffect } from 'react';
对，已移除这个改动

2024-09-05 06:45 UTC, MrWindlike commented on packages/refine/src/components/PodShellModal/PodShell.tsx
> +    const message = `4${base64Encode(
改变终端大小的命令，已改成枚举类型

2024-09-05 06:45 UTC, MrWindlike commented on packages/refine/src/components/Shell/index.tsx
> +export const Shell = React.forwardRef<ShellHandler, ShellProps>(function Shell(props: ShellProps, ref) {
已补充

2024-09-05 06:49 UTC, MrWindlike commented on packages/refine/src/components/Form/FormModal.tsx
> +export const FullscreenModalStyle = css`
已修改

2024-09-14 06:55 UTC, merged